export const CREATE_NEW_STATE = 'CREATE_NEW_STATE';
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const UPDATE_ORDER_SUMMARY = 'UPDATE_ORDER_SUMMARY';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const RESET_ORDER = 'RESET_ORDER';